### ISSUE TITLE
Data Not displaying in the Student View of the Attendance Block.

### ISSUE THREAD

**Issue by kgcannon** [danmarsden/moodle-block_attendance#12]
I have the attendance block and module configured on my Moodle site. The block will not display any information in the student view. Although 2 attendance sessions have been recorded, the block in the students view shows the "Taken sessions" as 0 and the "Points over taken sessions" as 0/0. The "Percentage over all sessions" is listed as "0" as well.

**Comment by danmarsden** [comment]
What version of Moodle, What versions of the attendance plugin and block do you have installed? - Please make sure you have the latest versions of the attendance block and attendance plugin.

**Comment by kgcannon** [comment]
Thanks Dan. We recently upgraded. The Moodle site is version 3.1.3, the attendance block is 3.2 (2016050900), and the attendance activity is 3.1.0.3 (2016052201).

Kattrina

**Comment by danmarsden** [comment]
ok - please upgrade the block you are using to the latest version which should fix this for you.

**Comment by kgcannon** [comment]
Hi Dan,

I upgraded to the latest block and the problem persists. Has no one else experienced this?

Thank you,
Kattrina

**Comment by danmarsden** [comment]
it does sound like #11 which was fixed in the latest version but it's possible there is another issue there. I haven't got time to look into this at the moment though - let me know if you track any other information down. Make sure you update the Module to use the latest version as well.

**Comment by kgcannon** [comment]
Hi Dan,

This has been resolved. My admin had installed a previous version of the block. Installing the 3.2.1 version solved the problem.

Thank you for your time and patience.

All the Best,
Kattrina

**Comment by danmarsden** [comment]
thanks.

**Comment by Bronosky** [comment]
hello dan
I use v. 3.5.1, and after installing Attendance ... students do not appear to assign attendance. Any tips?
All the Best
Marcos

**Comment by Bronosky** [comment]
The problem was in the permission mod / attendance: canbelisted, it should be with "enable".
Thank you
